from enum import Enum


class PlotType(Enum):
    PLOT_2D = "2D"
    PLOT_3D = "3D"
    PLOT_3D_BLOCK = "3D-Block"


DEFAULT_FIG_WIDTH = 6.0
DEFAULT_FIG_HEIGHT = 4.0
DEFAULT_FIG_FACECOLOR = "#FFFFFF"
DEFAULT_FIG_EDGECOLOR = "#FFFFFF"
DEFAULT_AXES_FACECOLOR = "#FFFFFF"
DEFAULT_LINE_COLOR = "#00f900"
DEFAULT_LINE_WIDTH = 2.0
DEFAULT_LINE_STYLE = "solid"
DEFAULT_MARKER = ""
DEFAULT_SHOW_GRID = True
DEFAULT_GRID_COLOR = "#CCCCCC"
DEFAULT_GRID_LINESTYLE = "solid"
DEFAULT_GRID_LINEWIDTH = 0.8
DEFAULT_SHOW_LEGEND = False
DEFAULT_LEGEND_LOCATION = "best"
DEFAULT_LEGEND_FONTSIZE = 10
DEFAULT_LEGEND_FACECOLOR = "#FFFFFF"
DEFAULT_XLABEL = "X-Achse"
DEFAULT_YLABEL = "Y-Achse"
DEFAULT_XLABEL_FONTSIZE = 12
DEFAULT_YLABEL_FONTSIZE = 12
DEFAULT_TITLE_FONTSIZE = 14
DEFAULT_TITLE = "Mein Plot"
DEFAULT_FONT_FAMILY = "sans-serif"
DEFAULT_GRID_X = 10
DEFAULT_GRID_Y = 10
DEFAULT_BLOCK_FRACTION = 0.8
DEFAULT_HEIGHT_SCALE = 5.0
